### ISSUE TITLE
[macOS] while running 1. autonomous exploration

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [mnotgod96/AppAgent#3]
Please enter the description of the task you want me to complete in a few sentences:

Task: Search for the user Bill Gates and follow him
Round 1

Thinking about what to do in the next step...

Traceback (most recent call last):
  File "/Users/harsha/Desktop/phone/AppAgent/venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harsha/Desktop/phone/AppAgent/scripts/self_explorer.py", line 127, in <module>
    rsp = ask_gpt4v(content)
  File "/Users/harsha/Desktop/phone/AppAgent/scripts/model.py", line 27, in ask_gpt4v
    if "error" not in response.json():
  File "/Users/harsha/Desktop/phone/AppAgent/venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mnotgod96** [comment]
Make sure you have filled out the OPENAI_API_KEY in the config.yaml file and the key has access to GPT-4V.
