### ISSUE TITLE
自动探索报错 requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jiangsiYang** [mnotgod96/AppAgent#31]
(venv) PS E:\AppAgent> python learn.py
Warning! No module named 'sounddevice'
Warning! No module named 'matplotlib'
Warning! No module named 'keras'
Welcome to the exploration phase of AppAgent!
The exploration phase aims at generating documentations for UI elements through either autonomous exploration or human demonstration. Both options are task-oriented, which means you need to give a task description. During autono
mous exploration, the agent will try to complete the task by interacting with possible elements on the UI within limited rounds. Documentations will be generated during the process of interacting with the correct elements to pro
ceed with the task. Human demonstration relies on the user to show the agent how to complete the given task, and the agent will generate documentations for the elements interacted during the human demo. To start, please enter the main interface of the app on your phone.

Choose from the following modes:
1. autonomous exploration
2. human demonstration
Type 1 or 2.

1
What is the name of the target app?

youtube
Warning! No module named 'sounddevice'
Warning! No module named 'matplotlib'
Warning! No module named 'keras'
List of devices attached:
['2210810']

Device selected: 2210810

Screen resolution of 2210810: 1080x2340

Please enter the description of the task you want me to complete in a few sentences:

Search music video songWonderful Tonight andleave a praising comment
Round 1

Thinking about what to do in the next step...

Traceback (most recent call last):
  File "E:\AppAgent\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\python3_10\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\python3_10\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python3_10\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AppAgent\scripts\self_explorer.py", line 127, in <module>
    rsp = ask_gpt4v(content)
  File "E:\AppAgent\scripts\model.py", line 27, in ask_gpt4v
    if "error" not in response.json():
  File "E:\AppAgent\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yonuyeung** [comment]
同样的问题，请问您解决了吗？

**Comment by yz93** [comment]
This is usually an Internet connectivity issue. Check that you have Internet and that you can visit OpenAI website and log into your account?

**Comment by zhelloworld123456** [comment]
>可以留个微信吗？共同交流
